

## 에러 & 예외 처리

### 1. 문법 에러(Syntax Error)

* 에러 발생 시 `syntax error`라는 키워드와 함께, 에러의 상세 내용을 보여준다.
* `파일이름`과 `줄 번호`, `^` 문자를 통해 파이썬이 코드를 읽어 들일 때(`parser`) 문제가 발생한 위치를 표현합니다.
* `parser`는 줄에서 에러가 감지된 가장 앞의 위치를 가리키는 작은 화살표(`^`)를 표시한다.
* EOL ERROR OF LINE
* EOF ERROR OF FILE
  

### 2. 예외(Exception)

* 문법적으로는 옳지만, 실행시 발생하는 에러이다.
* 아래 제시된 모든 에러는 `exception`을 상속받아 이루어진다.



### 3. 예외 처리(Exception Handling)

`try`&`except`

`try`문을 이용하여 예외 처리를 할 수 있다.

```python
try:
    <코드 블럭 1>
except(예외):
    <코드 블럭 2>
```

* `try`아래의 코드블락(code block)이 실행된다.
* 예외가 발생되지 않으면, `except`없이 실행이 종료 된다.
* 예외가 발생하면, 남은 부분을 수행하지 않고, `except`가 실행된다.

```python
try:
    num = input('값을 입력하시오 : ')
    print(int(num))
except:
    input('숫자를 입력하시오 :')
```



#### (1) 에러 메시지 처리 `as`

`as`키워드를 활용하여 에러 메시지를 보여줄 수도 있다.

```python
try:
    <코드 블럭 1>
except 예외 as err:
    <코드 블럭 2>
```

```python
try:
    empty_list = []
    print(empty_list[-1])
execpt IndexError as error:
    print(error)
```



#### (2) 복수의 예외 처리

 하나 이상의 예외를 모두 처리할 수 있다.

괄호가 있는 튜플로 여러 개의 예외를 지정할 수 있다.

```python
try:
    <코드 블럭 1>
except(예외1, 예외2):
    <코드 블럭 2>
```

```python
try:
    <코드 블럭 1>
except 예외1:
    <코드 블럭 2>
except 예외2:
    <코드 블럭 3>
```

__*중요한 점은 에러가 순차적으로 수행됨으로, 가장 작은 범주부터 시작해야 한다__

```python
try:
    num = input('100으로 나눌 값을 입력하시오:')
    100/int(num)
except ValueError:
    print('글자가 아닌 숫자를 입력해주세요.')
except ZeroDivisionError:
    print('0으로는 나눗셈을 할 수 없습니다.')
except Exception:
    print('에러가 났습니다.')  # 가장 큰 범위의 에러표현(?)
```

    #####    - else

* 에러가 발생하지 않는 경우 실행 시킬 문장은 `else`를 활용한다.
* `else`는 `except`코드 뒤에 와야 한다.
* `try`코드 블럭이 예외를 일으키지 않았을 때, 실행되어야 하는 코드에 사용된다.

```python
try:
    <코드 블럭 1>
except(예외):
    <코드 블럭 2>
else:
    <코드 블럭 3>
```

```python
try:
    numbers = [1, 2, 3]
    number = numbers[3]
except IndexError:
    print('오류 발생')
else:
    print(number)
```

#####    - finally

* 어떤 경우에든 반드시 실행해야 하는 코드에는 `finally`를 활용한다.
* 즉, 모든 상황에 실행되어야만 하는 코드를 정의하는데 활용한다.
* 예외의 발생 여부와 관계없이 항상 실행된다.

```python
try:
    <코드 블럭 1>
except(예외):
    <코드 블럭 2>
finally:
    <코드 블럭 3>
```

```python
try:
    languages = {'python': 'good'}
    languages['java']
except KeyError as err:
    print(f'{err}는 딕셔너리에 없는 키입니다.')
finally:
    print('감사합니다.')
```

=> 'java'는 딕셔너리에 없는 키입니다.
     감사합니다.

#### (3) 예외 발생 시키기(Exception Raising)

#####    - raise

`raise`를 통해 예외를 강제로 발생시킬 수 있다.

```python
# 양의 정수 두개를 받아 몫을 출력하는 함수 `def my_div(num1, num2)를 작성하세요

```

#####    - assert

`assert`문은 예외를 발생시키는 다른 방법이다.

보통 상태를 검증하는데 사용되며 무조건 `AssertionError`가 발생한다.

```python
assert Boolean expression, error message 
assert type(1) == int, '문자열을 입력하였습니다.'
```

* 위의 검증식이 거짓일 경우에 발행한다.
* `raise`는 항상 예외를 발생시키고, 지정한 예외가 발생한다는 점에서 다르다.

```python
# 양의 정수 두개를 받아 몫을 출력하는 함수 `def my_div(num1, num2)를 작성. assert를 활용하여, int가 아닌 경우 AssertionError를 발생시키기
```

